---
deployment:
  tasks:
    - export DEPLOYPATH=/home/s28sheoe5xht/public_html/sambodhimusic.com
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp shows.html $DEPLOYPATH
    - /bin/cp video.html $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp modals.js $DEPLOYPATH
    - /bin/cp smoothScroll.js $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
